"""each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not
    exceed four million, find the sum of the even-valued terms."""

def fib_sequence(num):
    if num <= 1:
        return num
    else:
        return(fib_sequence(num-1) + fib_sequence(num-2))
list(fib_sequence(i) for i in range(1000) if fib_sequence(i) < 4000000)


