'''
How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
'''

import numpy as np
from itertools import product

a = list(range(2,101))
b = list(range(2,101))

res = []
possibilities = list(product(a, b))

for idx in range(len(possibilities)):
    ans = possibilities[idx][0] ** possibilities[idx][1]
    res.append(ans)

res = np.unique(res)
print("Distinct terms =", len(res))
